### ISSUE TITLE
FastCCI doesn't work

### ISSUE THREAD

**Issue by butko** [Commonists/fastcci#12]
Please see https://commons.wikimedia.org/wiki/Help_talk:FastCCI#It does not work

**Comment by butko** [comment]
Tool is writing “connecting” for few days.

**Comment by petermgrund** [comment]
Still down.

**Comment by dschwen** [comment]
Works now. I improved the database generation step so that it is not RAM bound anymore. Late last year the Commons category dataset grew beyond the RAM available in my Wikimedia Cloud VM. Using mmap I'm now only limited by disk space. This should give us a few years. In the process I also updated the OS of the VMs to Debian 11 (one VM pending).

**Comment by prototyperspective** [comment]
Created this issue before I noticed this one here: https://phabricator.wikimedia.org/T367652

It still has the problem or at least well after this issue has been closed. Could you reopen? You could test it with the example I linked but it probably fails on many large categories.
